/**
 * Created by chenshiying on 17/9/25.
 */
export const FIND_COMMUNITY_SUB_TOPIC_FOR_PAGE = 'COMMUNITYSUBTOPIC/FINDFORPAGE';
export const FIND_COMMUNITY_SUB_TOPIC_FOR_PAGE_FETCH = 'COMMUNITYSUBTOPIC/FINDFORPAGEFETCH';
export const FIND_COMMUNITY_SUB_TOPIC_FOR_PAGE_SUCCESS = 'COMMUNITYSUBTOPIC/FINDFORPAGESUCCESS';
export const FIND_COMMUNITY_SUB_TOPIC_FOR_PAGE_ERROR = 'COMMUNITYSUBTOPIC/FINDFORPAGEERROR';

export const FIND_MORE_COMMUNITY_SUB_TOPIC_FOR_PAGE = 'COMMUNITYSUBTOPIC/FINDMOREFORPAGE';
export const FIND_MORE_COMMUNITY_SUB_TOPIC_FOR_PAGE_SUCCESS = 'COMMUNITYSUBTOPIC/FINDMOREFORPAGESUCCESS';
export const FIND_MORE_COMMUNITY_SUB_TOPIC_FOR_PAGE_FETCH = 'COMMUNITYSUBTOPIC/FINDMOREFORPAGEFETCH';
