/**
 * Created by chenshiying on 17/9/25.
 */
export const FIND_TOPIC_FOR_PAGE = 'TOPIC/FINDFORPAGE';
export const FIND_TOPIC_FOR_PAGE_FETCH = 'TOPIC/FINDFORPAGEFETCH';
export const FIND_TOPIC_FOR_PAGE_SUCCESS = 'TOPIC/FINDFORPAGESUCCESS';
export const FIND_TOPIC_FOR_PAGE_ERROR = 'TOPIC/FINDFORPAGEERROR';
