/**
 * Created by chenshiying on 17/9/25.
 */
export const FIND_TOPIC_VIDEO_FOR_PAGE = 'TOPICVIDEO/FINDFORPAGE';
export const FIND_TOPIC_VIDEO_FOR_PAGE_FETCH = 'TOPICVIDEO/FINDFORPAGEFETCH';
export const FIND_TOPIC_VIDEO_FOR_PAGE_SUCCESS = 'TOPICVIDEO/FINDFORPAGESUCCESS';
export const FIND_TOPIC_VIDEO_FOR_PAGE_ERROR = 'TOPICVIDEO/FINDFORPAGEERROR';

export const FIND_MORE_TOPIC_VIDEO_FOR_PAGE = 'TOPICVIDEO/FINDMOREFORPAGE';
export const FIND_MORE_TOPIC_VIDEO_FOR_PAGE_SUCCESS = 'TOPICVIDEO/FINDMOREFORPAGESUCCESS';
export const FIND_MORE_TOPIC_VIDEO_FOR_PAGE_FETCH = 'TOPICVIDEO/FINDMOREFORPAGEFETCH';

export const FIND_TOPIC_INFO = 'TOPICVIDEO/FINDTOPICINFO';
export const FIND_TOPIC_INFO_SUCCESS = 'TOPICVIDEO/FINDTOPICINFOSUCCESS';
export const FIND_TOPIC_INFO_FETCH = 'TOPICVIDEO/FINDTOPICINFOFETCH';
