/**
 * Created by chenshiying on 17/9/25.
 */
export const FIND_TOPIC_FOR_PAGE = 'TOPICHOME/FINDFORPAGE';
export const FIND_TOPIC_FOR_PAGE_FETCH = 'TOPICHOME/FINDFORPAGEFETCH';
export const FIND_TOPIC_FOR_PAGE_SUCCESS = 'TOPICHOME/FINDFORPAGESUCCESS';
export const FIND_TOPIC_FOR_PAGE_ERROR = 'TOPICHOME/FINDFORPAGEERROR';

export const FIND_MORE_TOPIC_FOR_PAGE = 'TOPICHOME/FINDMOREFORPAGE';
export const FIND_MORE_TOPIC_FOR_PAGE_SUCCESS = 'TOPICHOME/FINDMOREFORPAGESUCCESS';
export const FIND_MORE_TOPIC_FOR_PAGE_FETCH = 'TOPICHOME/FINDMOREFORPAGEFETCH';
