/**
 * Created by chenshiying on 17/9/25.
 */
export const FIND_VIDEO_SEARCH_FOR_PAGE = 'VIDEOSEARCH/FINDFORPAGE';
export const FIND_VIDEO_SEARCH_FOR_PAGE_FETCH = 'VIDEOSEARCH/FINDFORPAGEFETCH';
export const FIND_VIDEO_SEARCH_FOR_PAGE_SUCCESS = 'VIDEOSEARCH/FINDFORPAGESUCCESS';
export const FIND_VIDEO_SEARCH_FOR_PAGE_ERROR = 'VIDEOSEARCH/FINDFORPAGEERROR';

export const FIND_MORE_VIDEO_SEARCH_FOR_PAGE = 'VIDEOSEARCH/FINDMOREFORPAGE';
export const FIND_MORE_VIDEO_SEARCH_FOR_PAGE_SUCCESS = 'VIDEOSEARCH/FINDMOREFORPAGESUCCESS';
export const FIND_MORE_VIDEO_SEARCH_FOR_PAGE_FETCH = 'VIDEOSEARCH/FINDMOREFORPAGEFETCH';

